### ISSUE TITLE
Change to .Net Standard so library can be used by .Net Framework as well

### ISSUE THREAD

**Issue by z93blom** [deinsoftware/colorify#13]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed

# Libraries

How was referenced the library in your project?

- [ ] It was referenced as project
- [X] It was referenced as NuGet package

## Expected Behavior
I would like to be able to use the library in an .Net Framework Console application. This is not possible since the package is targeted against .Net Core only.

By retargeting the library against .Net Standard (1.3) it would be possible to use in both .Net Framework and .Net Core applications.

## Current Behavior
Not possible to use the library in a .Net Framework application since it's only targeted against .Net Core.

**Comment by equiman** [comment]
I will add it, but need help about netstandards, because I never used this versions.

I found a lot of netstandards versions:
netstandard1.0
netstandard1.1
netstandard1.2
netstandard1.3
netstandard1.4
netstandard1.5
netstandard1.6
netstandard2.0

https://docs.microsoft.com/en-us/dotnet/standard/frameworks

Why use 1.3 and not other? Like 2.0

**Comment by equiman** [comment]
Also I found this... are you working in some kind of legacy project with netstandards?

> What's the difference between the new netstandardapp and netcoreapp TFMs?

netstandardapp is obsolete, netcoreapp replaces it.

> What, then, exactly is netcoreapp supposed to be?

netcoreapp is the target framework moniker for the .NET Core Platform. If you add netcoreapp to your project.json's frameworks section, then a build of your app will run on .NET Core.

https://stackoverflow.com/questions/36962930/whats-the-difference-between-the-new-netstandardapp-and-netcoreapp-tfms

**Comment by z93blom** [comment]
> Why use 1.3 and not other? Like 2.0

You generally want to go with the "earliest" one that supports everything you need. That way it can be used on all frameworks that support that version, or a later one. Any framework that supports 2.0 also supports 1.3 (and all the lesser versions). 1.3 was the earliest .Net Standard version that supported everything that was needed for your library.

> > What's the difference between the new netstandardapp and netcoreapp TFMs?

> netstandardapp is obsolete, netcoreapp replaces it.

I've never heard of netstandardapp. It is not the same as netstandard. (The .Net team really had a breakdown when it came to naming things when they started with the .Net Core suite of programs). See this page for more information about .Net Standard:

https://github.com/dotnet/standard/blob/master/docs/faq.md

In general - you should strive to use .Net Standard for all libraries, while end applications should target either .Net Framework or .Net Core (or Xamarin iOS, Android, etc. (Not really relevant for your library due to lack of Console, but you get the gist of it I hope)). That way libraries can be used across a much wider base.



> Also I found this... are you working in some kind of legacy project with netstandards?

No, I'm just working with a .Net Framework Console application. It could obviously be converted to a .Net Core application, but I think the proper way is to use .Net Standard for libraries.

**Comment by equiman** [comment]
OK, thanks I'm clear with you explanation. 
I will add support for netstandard1.3 and netstandard2.0 but I need help to test if it work correctly.

Could you do that?

**Comment by equiman** [comment]
I already publish a version adding Net Standard compatibility:
https://www.nuget.org/packages/dein.Colorify/2.4.0-beta1

Could you please test if work?

**Comment by z93blom** [comment]
Works beautifully.

**Comment by equiman** [comment]
OK, I'll release 2.4.0 version. Thanks!

**Comment by sandrock** [comment]
I am trying to use the nuget package from a .NET Framework project. It seems netstandard supports has been added in 2.4.0 and has been dropped afterwards. 

When I try to reference the latest (2.6.0) nuget:

```
Could not install package 'dein.Colorify 2.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Referencing 2.4.0 works fine. 

May you restore support for .NET Framework via the use of netstandard?

**Comment by equiman** [comment]
Hi @sandrock, at moment there are no plans to enable again previous version compatibility.

However, I need to update it to dotnet 6 and I'll try to add previous versions again, only if does not give me a lot of compatibility problems.

**Comment by sandrock** [comment]
I know framework compatibility can be hard to deal with on .net. 

> I need to update it to dotnet 6

Why do you need to update? As @z93blom said: <cite>You generally want to go with the "earliest" one that supports everything you need. </cite>. Is there something in net6.0 that will make the lib better? I understand you want your app to use the latest tech; but libraries should not get updated when it is not necessary, or else all consumers of the library will be forced to update too. 

From what I see, targeting only netstandard1.4 would support apps from all known frameworks out there. Your code does not seem to depend on anything netstandard does not support. Am I wrong?

**Comment by equiman** [comment]
>  Is there something in net6.0 that will make the lib better?

LTS compatibility.

> From what I see, targeting only netstandard1.4 would support apps from all known frameworks out there. Your code does not seem to depend on anything netstandard does not support. Am I wrong?

I think not. As said before, it does not give problems will be added.

> when?

That's the real problem. I'm actually on a project with short deadlines and don't have too much free time to do this. 
Is on my task list, but sincerely on the bottom.

**Comment by equiman** [comment]
@sandrock 2.7.0 version was released and supports `netstandard2.1`, `netcoreapp3.1`, `net5.0` and `net6.0` target frameworks. 

Please let me know if works.

https://www.nuget.org/packages/dein.Colorify/2.7.0

**Comment by equiman** [comment]
@sandrock have you tested if this new version works as you expected?

**Comment by sandrock** [comment]
In a net461 project:

> Could not install package 'dein.Colorify 2.7.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

> Could not install package 'dein.Colorify 2.7.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

> Install failed (project: ConsoleApp2, package: dein.Colorify v2.8.0) Could not install package 'dein.Colorify 2.8.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.


And with net472:

> Install failed (project: ConsoleApp2, package: dein.Colorify v2.8.0) Could not install package 'dein.Colorify 2.8.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by equiman** [comment]
@sandrock sadly I don't know what other configuration do I need to do to add the support to those versions, and I don't have too much time these days to investigate.

If someone knows the steps I feel glad to add them or accept a PR.
