### ISSUE TITLE
The nuget package is wrong

### ISSUE THREAD

**Issue by Darlan82** [deinsoftware/colorify#5]
The nuget package is wrong.
See the folder below.

![image](https://user-images.githubusercontent.com/10963814/36001208-b1bdc158-0d0c-11e8-9650-9660b8585028.png)

The .dll files must be in the correct folders.
Follow the example below.
![image](https://user-images.githubusercontent.com/10963814/36001259-e7ce62d4-0d0c-11e8-9fff-7c1ca37f8e92.png)

**Comment by equiman** [comment]
Thanks @Darlan82 ... you are right. This package was created with this file:
https://github.com/deinsoftware/colorify/blob/master/Colorify/Colorify.nuspec

I'll take a look of NuGet documentation in order to fixit:
https://docs.microsoft.com/en-us/nuget/reference/nuspec

**Comment by equiman** [comment]
@Darlan82 I'm from mac with VSCode and don't have access to NuGet Package Explorer.

Could you please check this new version?
https://www.nuget.org/packages/dein.Colorify/1.0.2

Thanks in advance.

**Comment by aeciolevy** [comment]
Hi @equiman 
Have you fixed? 
I tried to use it, but it does not work. 
I am with version 1.0.2 and 1.1.2 for ToolBox.

**Comment by equiman** [comment]
I'ts my first time creating NuGet packages but I think now it's fixed. 

![colorify-nuget](https://user-images.githubusercontent.com/933393/36404576-6e189cba-15b9-11e8-85ba-08ece5ea1b60.png)

Please update ToolBox library too:
Colorify: [1.0.3](https://www.nuget.org/packages/dein.Colorify/1.0.3)
ToolBox: [1.1.3](https://www.nuget.org/packages/dein.ToolBox/1.1.3)

I already test in Sample project and works. Changing config file, removing project reference and adding NuGet packager reference using this commands:

```
dotnet remove reference ..\Colorify\Colorify.csproj
dotnet remove reference ..\..\_devTB\ToolBox\ToolBox.csproj
dotnet add package dein.Colorify --version 1.0.3
dotnet add package dein.ToolBox --version 1.1.3
dotnet add package Newtonsoft.Json --version 10.0.3
```


And `Sample.csproj` look like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="dein.Colorify" Version="1.0.3" />
    <PackageReference Include="dein.ToolBox" Version="1.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

@Darlan82 and @aeciolevy please let me know if also works in your projects. 

Thanks to @Darlan82 for taking the time to open this issue.
