### ISSUE TITLE
No Package Class Suggestion when creating new object.

### ISSUE THREAD

**Issue by Jvella94** [deinsoftware/colorify#6]
# Prerequisites

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed

## Expected Behavior

When making a new Format object, there is a suggestion to use the class in the package.

## Current Behavior

There is no suggestion and trying to manually add it does not work either.

### Context

- Colorify Version: 1.0.2
- Operating System: Windows 7 Enterprise
- VS 2017 Professional
- Console App Project

**Comment by equiman** [comment]
This problem could be related to this another issue: [The nuget package is wrong](https://github.com/deinsoftware/colorify/issues/5)
Please upgrade the NuGet package reference and test again. 

I made a new class to test this issue, but I can't reproduce it. 
OminiSharp intellisense works fine in vscode.

![colrify-class](https://user-images.githubusercontent.com/933393/36406410-9120df46-15c4-11e8-9282-8de9da1667f6.gif)

C# Addon: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

Some time OmniSharp fail and need to be reloaded:
Open command palette with `Ctrl+Shift+P` and choose `OmniSharp: Restart OmniShrap` option.

Please let me know if all this solve the problem or I'm missing something.

**Comment by Jvella94** [comment]
Yes the above is what I was referring to.

What .NET Framework version does dein.Toolbox support? I've tried building on 4.0 and up but there is no reference for it resulting in the below error:

Could not install package 'dein.ToolBox 1.1.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Jvella94** [comment]
I didn't read fully and realised this is a Core not Framework package. But yeah to confirm the OmniSharp works for me now :+1:
