### ISSUE TITLE
Project does not compile after being cloned

### ISSUE THREAD

**Issue by sebagomez** [deinsoftware/colorify#8]
This has nothing to do with the tool itself. I cloned the repo and couldn't build it because there's a project reference to a project I obviously don't have. 

I did find that lib (Toolbox) in Nuget but I realized it's only used in a method Colors.txtStatus which is not being used. So, there's a dependency to something that it's not used. And thru that Toolbox dependecy there's also a dependency to Newtonsoft, which it is not being used either. 

I'm fixing it in my cloned repo, I'll be glad to ceate a pull request if you want.

**Comment by equiman** [comment]
It's this library:
https://github.com/deinsoftware/toolbox

You can clone it and change path on `colorify.csproj` file:

```
<!-- Packages -->
<ProjectReference Include="..\..\_devTB\ToolBox\ToolBox.csproj" />
```

Or change de project reference to nuget packages (I do it this way on Sample project).

Colorify depends of Toolbox project because needs Platform and Validation classes. And Toolbox depends of NewtonSoft.

Let me know if need more information.

**Comment by sebagomez** [comment]
That's what I did, I removed the project reference and added a Package reference, but I then realized it is not used. Colorify is only using one method from Toolbox which is not used anywhere in the Colorify code.

You can check it our removing the reference... the only thing that will fail is the `Colors.txtStatus` method, and that method can be removed since it's not being used inside Colorify.

**Comment by equiman** [comment]
I'll check the way to change status method, and receive only a boolean parameter. 
Then remove ToolBox and NewtonSoft dependency. 

Thanks!

**Comment by equiman** [comment]
It's done. I changed:

```
public static string txtStatus(bool isValid)
{
    return (isValid ? txtPrimary : txtMuted);
}
```

**Comment by sebagomez** [comment]
Cool, thanks!

I must add that the method `Color.txtStatus` is never used... at least not inside Colorify and I'm not sure what it is good for.

**Comment by equiman** [comment]
You Welcome!

I'm using txtStatus a lot on [HardHat ](https://github.com/deinsoftware/hardhat) project mainly on menu options. Then with txtStatus you can show an option as disable (txtMuted) or enabled (txtPrimary).

Take a look on Start method:
https://github.com/deinsoftware/hardhat/blob/master/HardHat/view/Project.cs

**Comment by sebagomez** [comment]
It looks that the functionality belongs to HardHat, and not Colorify, but ok 👌

Sent from mobile

________________________________

**Comment by equiman** [comment]
At first I think the same. But can be useful not only for HardHat, that's why I decided leave on Colorify project.

Thanks again! Your comments make strong this Library 👍
